server:
  port: 8100
  servlet:
    context-path: /admin

spring:
  profiles:
    active:
      - admin
  web:
    resources:
      static-locations: classpath:static/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vaccination?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456

# mybatis 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 2
      logic-not-delete-value: 1
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true

    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 白名单配置
whitelist:
  #所有用户开放
  any:
    urls:
      - /code/sms
      - /image/pub/view
      - /image/view


  #登录用户开放
  user:
    urls:
      - /**


  #静态资源
  static:
    urls:
      - /*.html/**
      - /*.png
      - /*.ico
      - /*.json
      - /static/**


pageSize: 10


#线程池
thread:
  pool:
    keepAliveSeconds: 2000
    maxPoolSize: 100
    corePoolSize: 10
